apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mandagsmiddag-database
  namespace: mandagsmiddag
spec:
  instances: 1
  inheritedMetadata:
    labels:
      recurring-job.longhorn.io/source: enabled
      recurring-job-group.longhorn.io/hetzner-backup: enabled
  storage:
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi
