apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mandagsmiddag-secret
  namespace: mandagsmiddag
spec:
  encryptedData:
    tmdb-api-key: AgAMUrrL0U/MNzqW7BrSpsYpupjnjxma9slFmpiLRyjMw/o+GalTi6/DnIMlha6TEvLnTyqZdV1tTYTZywMgXIQkUKnfUrzsh2oA5TYXR1mHgaDsyO0/MqffudsMe9D43TjVb9w+AT32UQTOA9+2V0KYgI6R1RrEcI3veZYkRQC0eLeZqt2O2QTIR29HTuqzlsirrv1bLnQB3sSp3wth9J76nxQc+MntvemCLqnJ8JSxBWMp3YZwS06t5w9AQZ4yZ8IDA0Vv+TOrvdL7IaAbfF/UgxOuDYqvRSvOUpXWGGoWdWSNZ9r0gGkI8w+9tFNbhMEcFTPSs8bGUoRCuRF1ma0CE9SJ0lY7vXhkNgywh7RnS5aMukJwJdzPWhTUSkgwDuSV/CITfwssCLxHDLSo/RGsd0LuDsxgCv24aMdwKRZWpcrhnhrcWcUSOU2IyhF8/KbxYljrJvJ5mlsiM7R8OLynKcI2tasTtTnYxV+2F+Lwm9SlQonCi0S+Ij945LFYl8zpy/uL9hCIEC03Gadu5AJJvTLCRZKyS0YGUjQawFixU+9EtkLGScaMvK2jyZhPG2V7kZ5wVatYf0U5qt3ScM8H2PJ7k2xJEYuj4ZCbEVU3araMd4dkUSwfDvzkMd+GiS542e6pXf247Y6vIPAms5b895+Fn3y4e4NYoUXoz3ZzOGn9b2+YZHx6FqAKvWzyL53p+xI2Ps4Dnyds4AWXJj/HM8BlrT5hUTx7WytVgQM5Nw==
  template:
    metadata:
      name: mandagsmiddag-secret
      namespace: mandagsmiddag
