apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mandagsmiddag-oidc-client-secret
  namespace: mandagsmiddag
spec:
  encryptedData:
    client-secret: AgCrPXRM7rX8DpNb9q6YhWdcUIoUeNyuG2HUQzUM8e5vDd7I2jyp/LfgiYCJ/K3Y2VBl5Op02rcyLBykjk7puVTVA08ny556A0sw0+UpS1gW9UGGKMAaK0n5Cq4FFfJ7675PDTgoVYJSH7Kr2f9SON2TiT7zcbB8AjWKUqRF5visXUmrM9nSadDzwXZE0Xw1mS1mFcELxU14QMXvgdQOjlUIOvfsmACoNsoBRqQ48A5HO1/Tuvi/0qbyj84C6tUrCAV9m15QN2rz1dbRvtaBUEHVxocmW26eD+/YMDn9U6ehGOQdAGuwhuEBG4gJaGkdzwf8UUZel2a+THb+oXTQ3g0+IV9zXgfXnLw/sL7w8Y062n1R0GkYh9wHVpkWM+2RISNDusdWDOlSbJNNgDdepBBfNakor6UC75rNrEKoXPj1ObuRrghhr2Y6SvyLxeWGkijNOW8JGIETEKigBYfzoNkOw6qeDLD8UKu8T2SkbpqtAyfHRdSaR5K6vkWaKdfDtC4skRd51YV6PathrALA5C/IV7jIIg8fzJ69MFX4H+iJ7dIfJTV60TMluPHggl2P18CrGjIz6ox7PjgbIJHL8tOOGoxstOsAnJ1HCiNd7UFfYZXgt4vsWyehrnezhK9TSAA8XPUEv4euwyU6Y5aNzN0h6MwBP0JZBM2nDTYLRtq76+lPJFzreyB0GYnkxdLXRLABQg+AfD/p333mQiXR32jNab6XqLETDlvHCcg17ct4LL6nufa1Jh++7n5FxP76c516WAmaYhwe0p+LVrLdYWqKwhmgXZgt4qO3r+JhymJxVq2Y7gliedw769NIfzsMoc6IoVNxUCXrnlzFqrMeOAXIVGf2emqDIRE4iaQSg4+oTw==
  template:
    metadata:
      name: mandagsmiddag-oidc-client-secret
      namespace: mandagsmiddag
