apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandagsmiddag-backend
  namespace: mandagsmiddag
  annotations:
    keel.sh/match-tag: 'true'
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 2
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        logs.bakseter.net/scrape: 'false'
    spec:
      containers:
        - name: mandagsmiddag-backend
          image: ghcr.io/bakseter/mandagsmiddag/backend:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HOST
              value: https://mandagsmiddag.no
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: mandagsmiddag-database-app
                  key: host
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mandagsmiddag-database-app
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mandagsmiddag-database-app
                  key: password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: mandagsmiddag-database-app
                  key: dbname

            - name: OIDC_ISSUER
              value: https://authentik.bakseter.no/application/o/mandagsmiddag/
            - name: OIDC_CLIENT_ID
              value: mandagsmiddag

            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://alloy.monitoring.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_METRICS_EXEMPLAR_FILTER
              value: trace_based
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment.name=production,k8s.cluster.name=homelab
          startupProbe:
            httpGet:
              path: /healthz
              port: http
            failureThreshold: 30
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      terminationGracePeriodSeconds: 45
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - mandagsmiddag-backend
              topologyKey: bakseter.net/physical-node
      securityContext:
        fsGroup: 65534
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 65534
