apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mandagsmiddag-backend-secret
  namespace: mandagsmiddag
spec:
  encryptedData:
    tmdb-api-read-access-token: AgAcWpQ2Zuu3CNzJfT8UobNQoV8n3YiKrAaheOpvWlgehLLTA7YySyH/oLgeH0BV2yzfpL4Da5+qwmtVGYoFCTraGmikCBtAguBv8gOEkiqkNd9MHoSS2b3eALZAeWbcVf98wAfWwnRPdZOQMyxqawlNjoarRUe9T2/OmuIR1GCwKDMprcYcqFud6Kv1IWO5fugilqbAaneqdyIas39or6uWW7XFDii4EItLV5PHioXajkKNcqajMHYfiWfaioztk45v1E7sFW4cG82uHFOBkClGnAeeLP5dd0ZxciYMgmwhLSQ7u4soDCvy9/liRpDeTxXik3aTuAJsic5CurSrn/E4FxX75wd7t+2OPfXsUqFyfI8Hp9cD2TlIkKoswb2nV+sEJAh8IVzl/hpAhN7RYP0RWn+cve8T1mE8Gu/nkbvAJP9nYiNbYEMM+AbwYCzdc8s9UvVYVKouExW/cPd0/6hrSbKQHeQ2frPr39/zNpt1tZvXSuLEFxoHV45wrbw9p3spN2ElI0Ia1MhMKetpH5gjBK3TldZLgKVowbUNfRK8Cf06ESKdS1d42cgKXVo8DmC9qpr/d2oCQcDT2wFJ6ENO6lFTPPIm/V4JXYZ0RLXYuFeYyKH7f8YfDeJkSZWVPQDocHyWCYpl5fM96x4WTIYFNw5af04SEcNp8r47VA4POUntw+IF9cMQEjDL/s5wtus88B88Cq+8bpWwYwonwOcs5PoH26qwele709BnkK1qQ8gs0XHvBnLmpNmu1ifBE/acekVIBALSqaQtq0ZtNJ9mKYAPe06i9pPH4jfgfiqSUcdHwN4JSksaGSs3+MKED2H4wBtpN4RItQ+FLldMvZj0LROsRmghob0QKCluqT6nkLViKN7z/ZqXZVv7qXoxPEz59mMoPi/XqEKm9nUxmIpbKVrdZl+DmM0TyQsCeF+2GYJmvI4AqFZstYUsMFtYCzSc1ahcpz1MHmDkGWUEHQ9FzLs5RT+s47/oZEa8ZPPU2Fngu+1aQxeTZpR+tOHCOw==
  template:
    metadata:
      name: mandagsmiddag-backend-secret
      namespace: mandagsmiddag
