name: Test, lint and format

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-test'
      cancel-in-progress: true
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_DATABASE_HOST: localhost
      TEST_DATABASE_NAME: postgres
      TEST_DATABASE_USERNAME: postgres
      TEST_DATABASE_PASSWORD: postgres
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: 'backend/go.sum'
          go-version-file: 'backend/go.mod'

      - name: Run integration tests
        run: cd backend && make test-integration

  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-lint'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: 'backend/go.sum'
          go-version-file: 'backend/go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: 'backend'
          args: '--timeout=5m ./...'

  format:
    name: Format
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-format'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache-dependency-path: 'backend/go.sum'
          go-version-file: 'backend/go.mod'

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Check code formatting
        run: cd backend && make format-check
