name: Test, lint and format

on:
  push:
    branches: [master]
    paths:
      - 'backend/**'
  pull_request:
    branches: [master]
    paths:
      - 'backend/**'

jobs:
  # TODO: add tests
  #
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   concurrency:
  #     group: '${{ github.workflow }}-${{ github.ref }}-test'
  #     cancel-in-progress: true
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v6

  #     - name: Setup Go
  #       uses: actions/setup-go@v6
  #       with:
  #         cache-dependency-path: 'go.sum'
  #         go-version-file: 'go.mod'

  #     - name: Run tests
  #       run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-lint'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          cache-dependency-path: 'backend/go.sum'
          go-version-file: 'backend/go.mod'

      - name: Run linter
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          working-directory: 'backend'
          args: '--timeout=5m ./...'

  format:
    name: Format
    runs-on: ubuntu-latest
    concurrency:
      group: '${{ github.workflow }}-${{ github.ref }}-format'
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          cache-dependency-path: 'backend/go.sum'
          go-version-file: 'backend/go.mod'

      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@latest

      - name: Check code formatting
        run: cd backend && make format-check
